### ISSUE TITLE
Mockup Changes

### ISSUE THREAD

**Issue by projectgoav** [projectgoav/studeso#1]
@mmckay99 has done done a good job with the Mockup! I've a few things I'd suggest:
- I think we should have a small icon beside the search bar and Bark! there as well, just so at the top, everyone still knows they are on Bark
- I think posts on the homepage should be limited to a certain line/character length. That way we can put more on the page and it looks slightly less cluttered with everything being 'roughly' a fixed width
- Move "Search / Post / Bark" to be inline with image and BARK! headline.

Other than that, some great work!

**Comment by mmckay99** [comment]
Cheers :)
1. Well is the top bar going to be common to all pages? Or the whole main upper logo/title part?
2. Yes I agree- but are the posts going to actually be that long that they'll need clipping?
3. Yes agreed :thumbsup:
