### ISSUE TITLE
@ used in tag models

### ISSUE THREAD

**Issue by SCOTPAUL** [projectgoav/studeso#10]
In 9e3f2b5, it seems that we're acting as though all tags start with '@' in the model. Since all tags are done this way, shouldn't they just have a name without the '@' before it? It just seems like this might make constructing tags a bit more of a pain, since we'll have to add '@' everywhere and we could just have the '@' there in the html, or in a method.

It's not a big deal, but it would mean that UserTags etc would have to be constructed with:

``` python
UserTag.objects.create(name="@" + username)
```

rather than:

``` python
UserTag.objects.create(name=username)
```

which could cause problems if we ever forget the '@'.

**Comment by ghost** [comment]
I agree I think it would make it a lot simpler, we can talk about this tomorrow if need be

**Comment by SCOTPAUL** [comment]
I just wanted to know since @projectgoav asked if I could update the population script, but I'd need to know the format of the tag names to do that. I'll leave it for now.

**Comment by projectgoav** [comment]
I hadn't even thought about that Paul. I agree with you. Tags shouldn't have the @ symbol and revert back to the original way!
