### ISSUE TITLE
CSS/JS Staticly Served?

### ISSUE THREAD

**Issue by projectgoav** [projectgoav/studeso#11]
Are we having a static CSS and JS files, or are we going to download them everytime from Bootstrap.com

I'd perfer to have a static version of the CSS and JS which we server each time, simply because my internet connection at home is very slow and each pages takes an AGE to download. 

If not, I suggest we remove them from the project

**Comment by mmckay99** [comment]
Yeah sorry, I couldn't get the static file paths to work so I just downloaded them from Boostrap, just change it to static paths! :smile:

**Comment by projectgoav** [comment]
Fixed in 7378371a
