### ISSUE TITLE
URL mapping of posts

### ISSUE THREAD

**Issue by mmckay99** [projectgoav/studeso#12]
I had to make the Post "slug" field non-unique, so I could populate the database with different posts with the same title. Can I suggest we make the url from the (unique) post ID?

`bark.com/bark/1405/`

In my opinion, the only time people are going to bother even looking at the post URL is when copy-paste it to share with someone- in which case a shorter length is optimal.

**Comment by SCOTPAUL** [comment]
In the URL proposal file we had /bark/postID/postSlug I think, which would allow for uniqueness while also allowing search engines to find pages more effectively. I'd stick with that, unless you guys really want short URLs.
