### ISSUE TITLE
Something has gone wrong after merge

### ISSUE THREAD

**Issue by ghost** [projectgoav/studeso#14]
Can't run the updated population script or access much of the server, something to do with no table auth_user? Could be something to do with the updated models

**Comment by ghost** [comment]
Also the index page has no table bark_post

**Comment by mmckay99** [comment]
Just delete the database and do `manage.py syncdb`, then rerun the population script?

**Comment by ghost** [comment]
Of course forgot that, nice job with the templates :P

**Comment by mmckay99** [comment]
So it's fixed? :smiley: and cheers haha

**Comment by ghost** [comment]
Yeah runs fine now
