### ISSUE TITLE
Searching AJAX

### ISSUE THREAD

**Issue by mmckay99** [projectgoav/studeso#15]
Sweet stuff Lewis! This is defininitely a crucial feature, it's going to be good if we can get it spot on.
Two things:
- If we're viewing a post, and THEN search, the URL gets confused?
- Can we change the URL to "search" instead of "Search", I feel this is not good practice somehow?

I'd fix it myself but I didn't want to  dive in!

**Comment by projectgoav** [comment]
Also re-search. When I search, nothing is returned to me? Is this correct?

**Comment by ghost** [comment]
Yeah like I said it's not functional at the moment (probably down to me missing something silly) but yeah like I said in the commit if you want to alter it go right ahead, I only put it up just as an idea of what to work on

**Comment by projectgoav** [comment]
Alright, sorry I've missed the commit messages. MB!

**Comment by ghost** [comment]
Also I noticed a typo in my ajax script that has now been fixed

**Comment by ghost** [comment]
Update: have it "working" but seems to consistently give the same two posts... will investigate

**Comment by ghost** [comment]
I don't think we should go ahead with the AJAX search stuff unless we have time at the end
