### ISSUE TITLE
Signup

### ISSUE THREAD

**Issue by mmckay99** [projectgoav/studeso#16]
Re: Ewan

I can't seem to be able to sign up? This is the message I get:

> IntegrityError at /signup/`
> 
> bark_userprofile.reg_code may not be NULL`
> 
> Request Method:    POST
> Request URL:   http://127.0.0.1:8000/signup/
> Django Version:    1.7
> Exception Type:    IntegrityError
> Exception Value:   
> 
> bark_userprofile.reg_code may not be NULL

I'm sure I remember seeing randint(100, 9999) somewhere but I can't find it now, is this related?

Cheers

**Comment by projectgoav** [comment]
The reg_code stuff should have been removed entirely from the project. I did it as a test to check that the email system was working. Lemme check the models.

**Comment by projectgoav** [comment]
Just checking there. I can register without problems at all. Have you made sure you've pulled the latest work?

**Comment by mmckay99** [comment]
Yeah, well I deleted the database and started again seemed to work now. Thanks anyway :+1:
