### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by projectgoav** [projectgoav/studeso#19]
What did we agree on being the user profile view?

Was it just when someone clicks the special user tag it goes to a normal tag page, but has the users tag as default on the top of the page and all their posts underneath it?

**Comment by SCOTPAUL** [comment]
I think so, yeah. I think users were also able to set the description of their user tag which would be shown too.

**Comment by projectgoav** [comment]
For the description, i've just put a Bio section into the UserProfile model (for now) Didn't think we could access the UserTag directly, but I believe we can?

**Comment by SCOTPAUL** [comment]
Yeah, you could just do

``` python
description =  UserTag.objects.get(name=username).description
```

**Comment by projectgoav** [comment]
Alright, thank you!
