### ISSUE TITLE
Next Team Meeting

### ISSUE THREAD

**Issue by projectgoav** [projectgoav/studeso#2]
Paul and I think we'll need 2 hours next week to complete the Powerpoint & extras before the Presentations.

We're proposing Thursday 10am (as before) <b>AND</b> Friday at 2pm or 3pm dependong on JOOSE's topic.

Will you be able to make it?

<b><i>What we need still need to do</i></b>
- Finish functional requirements
- User needs matrix (What even is that?)
- Finalize User Personas
- Sort out our URL mappings & get a Sitemap
- Finalize Mockups

<i>Ps - where were you Michael today? </i>

**Comment by ghost** [comment]
Yeah sounds good
