### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by projectgoav** [projectgoav/studeso#20]
As of  2bf38c9f28857b863e8556a5e2bfa2e12c5c3da0  we are using django-boostrap3 package from Pip.

Are we going to use this over staticly serving bootstrap css from the site?

**Comment by SCOTPAUL** [comment]
As far as I can tell, the css/js is still being served staticly. Looking through the source and inspecting network traffic it doesn't seem to make any outside requests.

I just added it for the ease of making forms. If you look at signup.html you can see how simple they are with django-bootstrap3.

**Comment by projectgoav** [comment]
Yea, I was looking at that. Only think is, that particular form is the only one where I use the forms file. The others I all have static forms which I created myself. I'll perhaps change this once I've styled the remaining ones.

I've modified your signin one (as I was just about to commit it when you did!) to report errors nicely.

**Comment by SCOTPAUL** [comment]
Yeah, I noticed that. It still helps a lot with stuff like pagination if we decide to use that at some point.

**Comment by projectgoav** [comment]
True true. Don't like how the fields are underneath each other however. Can't we style them in columns like the signin page?

**Comment by SCOTPAUL** [comment]
Hmm, I don't know. The documentation is pretty awful, but I'll try to find out.

**Comment by projectgoav** [comment]
That's the only think I dislike about it. I'll have a look later, but think I might as well get some forms at  least with static bootstrap code.

**Comment by SCOTPAUL** [comment]
I sort of fixed it, but the submit button floats all over the place for small screens. I can't work out why that is, but the columns look like the signin page for full screens.

**Comment by projectgoav** [comment]
The submit button seems to work for me? That's great work btw!

**Comment by SCOTPAUL** [comment]
I have an old version of firefox on this machine I think, that could be causing it. Good to know it works for you, I've been messing with it for ages!
