### ISSUE TITLE
Use of Django Forms

### ISSUE THREAD

**Issue by SCOTPAUL** [projectgoav/studeso#21]
A lot of the forms in the project are done in raw html, which prevents automatic styling with django-bootstrap3 and creates inconsistencies in the code.

I really think that we should move to Django's forms whenever possible, as I'd imagine that Leif would be likely to remove marks for these static forms due to it violating DRY.

Any thoughts?

**Comment by projectgoav** [comment]
I agree with you BUT, I always thought the forms had to be associated with a model. Since very view directly associate with one or require more information, is this going to be possible?

**Comment by SCOTPAUL** [comment]
I think it's only forms.ModelForm forms that have to be associated with a model. There are a bunch of other types which allow for more flexibility in the form.

**Comment by projectgoav** [comment]
Alright, I will look into doing that this week then!
