### ISSUE TITLE
Can't add tags to posts

### ISSUE THREAD

**Issue by mmckay99** [projectgoav/studeso#22]
I noticed when I added in the addPost form that only the username tag gets added to the Post "tags" field- not any ones specified during the form?

I'm not sure if this is a problem with:
- the form
- the model
- the post view

I'll check this out when I have time.

**Comment by SCOTPAUL** [comment]
Yeah, I noticed that. In addition, the list seems like it's not the best way to choose tags since there could be loads of them, I'll try to work on a solution to that tonight.

It could be useful to reuse some of the ajax search code that Lewis is working on, do you know if that works yet?

**Comment by projectgoav** [comment]
I don't think the search does anything yet. I've tried and it gives me some errors when I click the search button.

**Comment by ghost** [comment]
Yeah I haven't altered my Ajax stuff since I initially committed it but if you want to alter it so it's at least functional feel free

**Comment by SCOTPAUL** [comment]
I think I might have fixed the tagging issue, if you guys could test it too that'd be good.

**Comment by mmckay99** [comment]
Excellent work! I will test it.

Edit: I can't add tags at all, I tried using "@python @django", and "python django", and "#python #django"... am I missing something?

**Comment by SCOTPAUL** [comment]
Are you hitting return after each tag? I need to add some instructions on the page but after you type something you hit return and it gets added.

**Comment by SCOTPAUL** [comment]
Also, don't put the @

**Comment by ghost** [comment]
I tested it and it works fine,great job Paul

**Comment by mmckay99** [comment]
That was it! Yeah looks good. Great that it adds in new tags if you use ones that haven't been used before.

**Comment by SCOTPAUL** [comment]
Yeah, the only problem is that I haven't really figured out what to do about InstitutionTags yet, since anyone can add to any tag. I'll think about that tomorrow.

**Comment by projectgoav** [comment]
Think you need a rest Paul! You've been doing a power of work!
