### ISSUE TITLE
Search Function

### ISSUE THREAD

**Issue by projectgoav** [projectgoav/studeso#23]
The search function just seems to return a list of posts, in the same order, regardless of what you've searched.

If I search 'Populate' I expect to see the Populate.py post first, however it's not.
If I search 'SCOTPAUL' I expect to see all the posts by SCOTPAUL first, however the posts are in the same order.

**Comment by ghost** [comment]
I know I'll get working on it later today

**Comment by projectgoav** [comment]
Fixed in 4ba13350e06b640ef8c40be8db76bb59a104aa7e
