### ISSUE TITLE
Searching

### ISSUE THREAD

**Issue by mmckay99** [projectgoav/studeso#24]
**FAO: Lewis**

Fantastic work getting searching working! I think we can do it in one query though, I found this:

https://docs.djangoproject.com/en/1.7/topics/db/queries/#complex-lookups-with-q-objects

I think this is what we need, so I'll look into it once I've done the "view posts" view and template.

**Comment by ghost** [comment]
I agree but I tried using Q and I got a lot of errors, possibly because of post tags being a ManyToMany field, can always have another look tomorrow, important thing is that it's functional

**Comment by mmckay99** [comment]
Definetly. I'm trying to use them to combine the /tag1/tag2/ functionality in viewPosts, hopefully I can get it to work.

**Comment by ghost** [comment]
Search now uses Q in my latest commit
