### ISSUE TITLE
We don't support anonymous posting/commenting

### ISSUE THREAD

**Issue by SCOTPAUL** [projectgoav/studeso#25]
We haven't really talked about this feature for a while, do you guys still want to do it or should we scrap it?

**Comment by mmckay99** [comment]
Shouldn't be too hard, just a new flag in "Post" for "postedAnonymously", which can be ticked, and then an if-statement in the template:

`{% if posted_anonymously %} ... {% else %} view the user name {% endif %}`

**Comment by projectgoav** [comment]
I say get the site working, with posts and comments so we have something to demo. If we have time then we can add it in?

**Comment by mmckay99** [comment]
It's done bitches.

**Comment by SCOTPAUL** [comment]
If you go to a user's page and click "See more..." anonymous posts by that user still show up. Also, if @anonymous isn't a user I'm not sure we should make the tag green, since that duplicates it.

**Comment by mmckay99** [comment]
Is that working now? What do you mean by duplicates it? I just thought it reinforces the idea that a _user_ made this post, the _anonymous user_?

**EDIT: I need some help!** Where does the user tag actually get added to the Post tags (so we can not add it if it's anonymous)?

**Comment by SCOTPAUL** [comment]
Edit: Sorry, it's actually tagged in the Post model, in the save method.

**Comment by SCOTPAUL** [comment]
Nice work!
Fixed in ad934ea7efd9a4be8ac8a6e23a1fbab6487bdcb8
