### ISSUE TITLE
postlist.html v posts.html

### ISSUE THREAD

**Issue by mmckay99** [projectgoav/studeso#28]
I added posts.html when I made the initial templates- what's postlist.html? Is posts.html now redundant, can we delete?

Cheers

**Comment by SCOTPAUL** [comment]
postlist.html is used to populate the index, and presumably tag views in the future. I think posts.html can be deleted, but you might want to wait to see if @projectgoav was using it anywhere.

**Comment by mmckay99** [comment]
Can we rename "postlist.html" to "singlePostView.html" or something useful, and then make "posts.html" use singlePostView to render each post? I just think we have redundancy here- the index page, search results, viewing posts by tag, should all use the same HTML to render the list of posts.
- I tried to fix this, but I wasn't sure where "get_view" is made, or "postlist.html" referenced? Cheers

**Comment by SCOTPAUL** [comment]
get_view is in the postlist.py file, which is in templatetags. As for reducing redundancy, I agree but I haven't worked much with the structure of the html files so I don't know if there's a reason we have so many.

**Comment by projectgoav** [comment]
get_view abstracts the postview out of the templates. Everytime you want a post, call get_view and past the post. It returns a formatted panel, with header, content, formatted tags and corrected links through it. 

I agree. Perhaps even just get a list which calls get_view repeatedly with a list. As for naming, I don't mind, whatever works.

I was to replace the same loop being used in the index, profile, search and tag view lists. Now we just get a list of posts and pass to the separate template to reduce repetition.
