### ISSUE TITLE
Bark! Logo

### ISSUE THREAD

**Issue by mmckay99** [projectgoav/studeso#29]
@projectgoav I take it you made the current logo? Is that something we want to stick with?

Cheers

**Comment by projectgoav** [comment]
I don't mind. I just made it to fix the navabr not displaying properly with the bigger image. It's up you, the team.

**Comment by mmckay99** [comment]
Do you think we could make the navbar a little taller? I managed to make it taller but couldn't get the buttons and stuff to be centred vertically.

**Comment by projectgoav** [comment]
I've been trying for months to get the items centered vertically, but to no avail. Stack and the Bootstrap website aren't much use.

Sent from my Windows Phone

**Comment by projectgoav** [comment]
Bark Logo doesn't sit right in page. It's squished into the corner of the screen.

![screenshot from 2015-03-20 10 03 17](https://cloud.githubusercontent.com/assets/6363155/6749464/6fb66fae-cee8-11e4-94bb-75fe33977503.png)

**Comment by SCOTPAUL** [comment]
Now fixed.
