### ISSUE TITLE
Could we leave the ranking script running?

### ISSUE THREAD

**Issue by SCOTPAUL** [projectgoav/studeso#30]
I'd like to make sure that the ranking script is efficient enough not to deplete our pythonanywhere computation time during the presentation. Could we start rankLoop.sh running now so that we can see if we need to make the time between rankings longer?

**Comment by projectgoav** [comment]
Yea, we can try that. Is the script there?

**Comment by SCOTPAUL** [comment]
Yeah, it's in the same directory as manage.py

**Comment by projectgoav** [comment]
Got it! I hadn't pulled into the pythonanywhere.
I've set it to run every 5secs. I'm not sure if it runs when I close the console, but we'll find out.

**Comment by projectgoav** [comment]
Update: Running ranking every 5seconds used 10% CPU in under 5mins. I suggest running it every 30mins. We can speed it up for when we're doing our presentations?

**Comment by projectgoav** [comment]
Script running is fine. We've been tarpitted and site works perfectly fine. I'll see it to run ever 30mins/hour

**Comment by mmckay99** [comment]
Do we need to have the ranking script running when presenting? Surely the content of the site won't be changing, so the ranks won't need updating?

**Comment by SCOTPAUL** [comment]
I meant that we should have it running while demonstrating in the lab, to show that it works. I'm not sure if we're running it locally or on pythonanywhere for that though.
