### ISSUE TITLE
Slugifying tag names breaks tag view

### ISSUE THREAD

**Issue by SCOTPAUL** [projectgoav/studeso#31]
For example '@JOOSE' won't show any posts when clicked on, since slugify makes the url for it

```
/barks/joose
```

rather than

```
/barks/JOOSE
```

This also breaks on tags with special characters. Would it be possible to move this back to the old way?

**Comment by projectgoav** [comment]
Should be fixed to use names over slugs. I don't see the need for a slug as the name is always going to be unique, we don't need another thing that is unique in the database.

**Comment by mmckay99** [comment]
The reason I think we should use slugs for tags is the same reason we use slugs for post titles- URLS shouldn't be uppercase etc.

If we break the rule for tags then why bother using slugs for posts as well.

**Comment by SCOTPAUL** [comment]
I don't mind whether we use names or slugs, but the current implementation is broken.

**Comment by projectgoav** [comment]
I didn't think the slug in a post was ever used? If you just give the proper id number, the post still displayed?

**Comment by SCOTPAUL** [comment]
It's used more for making the URL human readable than anything else, I don't think it's actually required.

**Comment by mmckay99** [comment]
> therefore should be normalized to lowercase

It's recommended- so I personally think (if it's not too much trouble) we should keep it lowercase and slugified- but whatever the majority thinks.

From [RFC 3986](http://tools.ietf.org/html/rfc3986).

Also:

> Special symbols must sometimes be percent-encoded

From [Wikipedia](http://en.wikipedia.org/wiki/Uniform_resource_locator)

Edit: Do you want to just ensure tag names are lowercase and don't contain "special" characters?

**Comment by SCOTPAUL** [comment]
I'd agree if we had more time, but at the moment usernames can be in any case, for example, so while "John" and "john" could be different users, each with a different user tag, they would have to share a URL mapping for their posts. There are a few other places where problems like this could be introduced too. It would require a decent amount of messing with models and testing, and I don't know if it should be a priority.

Obviously if you really want to change it then feel free, but the most important thing is that it works.

**Comment by mmckay99** [comment]
Ok just go for it now- I'll investigate later.
