### ISSUE TITLE
Searching Multiple Things

### ISSUE THREAD

**Issue by projectgoav** [projectgoav/studeso#32]
With the search function, is it possible to search for 2 things at once? Like if I search "Tag1 Tag2" what should I get? Everything with "Tag1 Tag2" or everything with "Tag1" and/or "Tag2"

Also - what does related tags do? All I get is the search term I have entered.

**Comment by ghost** [comment]
It only searches for one thing at a time

**Comment by SCOTPAUL** [comment]
That seems like a fairly significant problem, one of our earliest examples for the search was that we should be able to search for "python dictionary" to find posts tagged with @python AND @dictionary.

**Comment by ghost** [comment]
I'm currently working on making a follow tag button but once I finalise that I can have another look at dealing with multiple search queries

**Comment by ghost** [comment]
The only problem I could see is how it would affect content and title searches but I suppose it would still return the same results

**Comment by mmckay99** [comment]
Should be fixed
