### ISSUE TITLE
"Follow Tag" buttons

### ISSUE THREAD

**Issue by mmckay99** [projectgoav/studeso#33]
I personally think it looks too messy having buttons, and looked cleaner with:

`Tags: python (follow), java (follow)`

What do you guys think?

**Comment by ghost** [comment]
I thought it would look better with a button but maybe the style of the button could possibly be changed, up to you but personally I'd prefer to see a button there

**Comment by mmckay99** [comment]
Okay, just that at the moment it's a bit messy when there's multiple tags

**Comment by ghost** [comment]
I'll delete the button in the search template then but we should keep it in the tag view

**Comment by ghost** [comment]
Changes made in 49edc2904e6c2575cd232732b53649d5d429e9c9 including (follow) next to tags
