### ISSUE TITLE
Following a Tag doesn't work on occasion.

### ISSUE THREAD

**Issue by projectgoav** [projectgoav/studeso#34]
Trying to follow the CS tag or C++ tag fails.

![screenshot from 2015-03-20 22 06 33](https://cloud.githubusercontent.com/assets/6363155/6761673/67166e70-cf4d-11e4-850a-2757c900e5ac.png)

**Comment by SCOTPAUL** [comment]
In posts.html we have `tag.slug` instead of `tag.name`, changing that fixes most of them.

It still breaks on c++ though, possibly because of the '+' character not being properly encoded.

**Comment by mmckay99** [comment]
Yeah this is to do with the slug. I'll fix it.

**Comment by projectgoav** [comment]
Also changing the URL to sense (.*) seems to fix all our special character problems!
