### ISSUE TITLE
Creating new Post

### ISSUE THREAD

**Issue by projectgoav** [projectgoav/studeso#36]
When I create a new post with a user with gla.ac.uk email but are posting to bristol.ac.uk I still create the post, however the birstol.ac.uk tag is removed and I'm left with "@" then any other tags in the post.

![screenshot from 2015-03-21 13 26 08](https://cloud.githubusercontent.com/assets/6363155/6765206/de67babc-cfcd-11e4-9300-529c920e5014.png)

**Comment by SCOTPAUL** [comment]
Should be fixed now
