### ISSUE TITLE
User profile image

### ISSUE THREAD

**Issue by mmckay99** [projectgoav/studeso#38]
Is this working? I can't upload .jpg, .png, etc, what am I missing? Just in case we wanted to show we can have custom user profile images in the presentation.

Cheers

**Comment by SCOTPAUL** [comment]
There's nothing in request.FILES when the form is submitted. I'll try to work out why.

**Comment by mmckay99** [comment]
Unreal.

**Comment by SCOTPAUL** [comment]
I know, that missing enctype gets me every time.
