### ISSUE TITLE
What else needs done?

### ISSUE THREAD

**Issue by mmckay99** [projectgoav/studeso#39]
Off work tomorrow and can work on something

**Comment by ghost** [comment]
I think we have most of the website done, error checking might be a good idea so try using the site (we might not have noticed the image upload issue). One thing we thought about as an extra was autocomplete in search? If you wanted to have a go at that if you wanted something to do

**Comment by SCOTPAUL** [comment]
Yeah, autocomplete working would be nice. Other than that, I think we should be working on a general code cleanup (removing prints, adding comments where required etc), since I don't think there are any more features to work on.

**Comment by ghost** [comment]
Issue #7 has something there that might be useful for autocomplete

**Comment by SCOTPAUL** [comment]
I think we could only do that one of we used ajax to narrow down the tags a bit. Passing every tag in the system into the HTML seems like it would result in some really large amounts of data getting sent.

**Comment by ghost** [comment]
Good point and given the lack of CPU time on PythonAnywhere this might lag during the live demo

**Comment by ghost** [comment]
And while I remember it'd be a good idea if the population script had like values for posts/comments as it would look better for the top posts on the index page
