### ISSUE TITLE
User tags in post view link to /barks/username rather than user profile

### ISSUE THREAD

**Issue by SCOTPAUL** [projectgoav/studeso#40]
Clicking on a user tag in any of the views links to all of their posts rather than their user profile. As far as I can tell, this means that there is no way to view another user's profile except by manually typing the URL.

Is this intentional?

**Comment by ghost** [comment]
I noticed that too, but one thing to consider is that the user profile view still shows posts with that user's tag in it, we could change it to reflect this if that's okay with everyone?

**Comment by ghost** [comment]
Fixed in b9101e94a5e6009d49d106f07d704e2e15e36f9b
