### ISSUE TITLE
Bark Python Anywhere - 1 Error

### ISSUE THREAD

**Issue by projectgoav** [projectgoav/studeso#41]
bark.pythonanywhere.com now runs code version: 23182fefa7c3f3152ebb7538c361008eca9b776c

Everything works fine, including the sending of emails, apart from tag-following. 

It works on a local copy of the site, but not pythonanywhere. There's no errors or exceptions thrown at any point and the database contains entries that the tags are being followed, the sidebar doesn't seem to display them.

NOTE: It's also showing a lot of the HTML/CSS errors I've fixed a few times. Can you please make sure you PULL before you PUSH any changes. Thanks!

**Comment by 2085749D** [comment]
There's also an issue with post likes not being displayed properly, they appear on the admin page though

**Comment by ghost** [comment]
It might be alright seeing as Leif will create a local copy and can see the tag following in action for himself

**Comment by SCOTPAUL** [comment]
Following tags appears to also be broken on my local version.

**Comment by mmckay99** [comment]
On my local version I can follow tags and it appears in the admin interface?

**Comment by SCOTPAUL** [comment]
Does it show in the sidebar? I can see the follows in the database but my sidebar never updates.

**Comment by mmckay99** [comment]
No. I put a print statement in the first line of get_sidebar and it's never printed? On page refresh etc.

How exactly is get_sidebar meant to be called?

**Comment by projectgoav** [comment]
If you have no call to get_sidebar then you shouldn't see a sidebar at all :/

**Comment by projectgoav** [comment]
adding a print into my local copy and into the pythonanywhere copy the sidebar is getting called. Must be something to do with the tag generation code.

**Comment by SCOTPAUL** [comment]
Yeah, I can see a print.

**Comment by mmckay99** [comment]
My mistake- it's printing now.

**Comment by SCOTPAUL** [comment]
I think I fixed it, could you guys pull and try it now?

**Comment by ghost** [comment]
I also fixed a typo in sidebar.html

**Comment by projectgoav** [comment]
Yeah Paul. That's working in pythonanywhere now! Thanks :)

(fixed in eacb50a85e034f3d16249d44f7d0f702ffd79fd4)

**Comment by mmckay99** [comment]
Good job :+1:
