### ISSUE TITLE
Searching with "AND"

### ISSUE THREAD

**Issue by mmckay99** [projectgoav/studeso#42]
I've implemented searching like:

`operator + python`
`operator | python`

and it seems to work, but obviously doesn't work for the "C++" tag: do you want to use the `&` character for and?

**Comment by projectgoav** [comment]
Searching with + seems to work fine for me. Only thing I'd say is that related tags is a bit funny, should it so that many tags?

![screenshot from 2015-03-22 12 55 35](https://cloud.githubusercontent.com/assets/6363155/6769422/bdf4ebfe-d092-11e4-97c4-34487277c9f9.png)

**Comment by SCOTPAUL** [comment]
Wow

**Comment by mmckay99** [comment]
It's a bug, fixing it now

**Comment by ghost** [comment]
I think it might be a good idea if we cut that down just a tad

**Comment by mmckay99** [comment]
Fixed! :smile: 

Edit: just don't search for C++...

**Comment by SCOTPAUL** [comment]
Searching for something like "a" or just an empty space produces the same sort of output as above.

**Comment by mmckay99** [comment]
I know- but If you don't want to see 
- "gla.ac.uk" for "a" (bad)

It's going to be tricky keeping 
- "python-lists" for "python" (good)

or
- "advanced_programming3" for "programming"

IMO if the user searches "a" they clearly wanted all tags or posts containing "a", what else would they want.

**Comment by SCOTPAUL** [comment]
I'm think there should be some sort of cap on the number of tags that can show up there, imagine if we had thousands of tags and a user searched for "a". There would be pages of this stuff. Is there any way with the current system to determine what tags are the most relevant in that list?

**Comment by SCOTPAUL** [comment]
Also, searching for "" shouldn't really be possible, should it?

**Comment by mmckay99** [comment]
- Okay, I'll cap the number of tags at 15.
- What do you imagine happening if the user searches ""?

It's quite tricky to do "relevancy", although one fix I can think of is to order related tags by the difference in length to the search query: so if the user searches "a" the first related tag should be "a"?

**Comment by SCOTPAUL** [comment]
Looking at other sites, it seems like nothing should happen, the form isn't submitted. If that's difficult to do then I suppose it's not a big deal.

**Comment by mmckay99** [comment]
No that's quite easy, do you want to say "No results"  (Reddit does this) or just nothing?

**Comment by SCOTPAUL** [comment]
Yeah, no results or whatever would be fine. I just thought that an empty search shouldn't return any meaningful results.

**Comment by mmckay99** [comment]
(https://github.com/projectgoav/studeso/commit/ce10603e1d2fa60a1a4aa1bd0b8739f6ef4dda1b)
