### ISSUE TITLE
Is it possible to unfollow a tag?

### ISSUE THREAD

**Issue by SCOTPAUL** [projectgoav/studeso#43]
I can't seem to find any way to do it, and it seems like something that a user might want to do.

**Comment by mmckay99** [comment]
Shouldn't be too hard to implement the view for- do you think an `(x)` beside the follow button is sufficient?

**Comment by SCOTPAUL** [comment]
Yeah, either that or just making the button say "unfollow" and then in the view just delete the following if it already exists. What do you think?

**Comment by mmckay99** [comment]
I added a view for unfollowing a tag- just not sure how to do unfollow?

I think if we add an "unfollow" button beside "follow", users might forget if they are following a tag or not?

**Comment by projectgoav** [comment]
Delete the record out the database.

Psuedo-Code:

```
Tag = TagFollowing.all.filter(user=user, tag=tag)
if Tag:
    tag.delete()
```

**Comment by SCOTPAUL** [comment]
I meant that if the user was already following the tag, the button would say "Unfollow" instead. You'd have to pass something into the tag view to say if the tag had been followed or not, that's the only issue.

**Comment by mmckay99** [comment]
> I meant that if the user was already following the tag, the button would say "Unfollow" instead. You'd >have to pass something into the tag view to say if the tag had been followed or not, that's the only >issue.

Yeah I think this is tricky- we have to pass a list of all the tags the user follows into the template

**Comment by SCOTPAUL** [comment]
As far as I can tell, in viewPosts we already pass in a list of tags found by the query. Wouldn't it just be a case of checking each of those in the view, doing

``` python
for tag in tags:
    tag.followed_by_user = False
    if tag in user_profile.followed_tags:
        tag.followed_by_user = True
```

before they are put into the context dictionary?

I could be completely misunderstanding the code, but it seems possible to do without passing in all the user's followed tags.

**Comment by mmckay99** [comment]
I think it should be working in (https://github.com/projectgoav/studeso/commit/2c33b06b8c5757c91aa102aad8b84a97f93bd169)
