### ISSUE TITLE
Wasn't the index view supposed to be made up of posts with followed tags?

### ISSUE THREAD

**Issue by SCOTPAUL** [projectgoav/studeso#44]
I can't remember for certain, but I thought that if a user followed tags then their index page should've been made up of posts with tags they followed (similar to Reddit). At the moment it's just every post.

If this is something we wanted I wouldn't mind working on it now.

**Comment by mmckay99** [comment]
Yeah I think this is what we agreed- and users that aren't logged in would just see everything. Are you sure, I don't mind working on it if you want a lunch break?

**Comment by SCOTPAUL** [comment]
Yeah, I think so. We might need to automatically have users follow some tags to initially populate that view though (again, similar to Reddit).

And yeah, feel free to work on it. I'm going to be away for the next hour or so anyway.

**Comment by mmckay99** [comment]
Yes... okay I'll look into it.

**Comment by mmckay99** [comment]
Okay I think I have it working but I'd really appreciate it if you guys could make sure it works:

(https://github.com/projectgoav/studeso/commit/a82f778a21937d869fbc170530f1210a014f3b88)

**Comment by SCOTPAUL** [comment]
It seems to work, but if you create a new user they see no posts, which may be quite confusing to a new user. Do you think we should follow some tags automatically as I mentioned above?

**Comment by mmckay99** [comment]
Or subscribe new users to "all" by default? (All posts are tagged with "@all")?

**Comment by SCOTPAUL** [comment]
Ehh, I don't know. If all posts are visibly tagged with @all that seems like it could look a bit ugly. We could hide it or something but I'm not sure. Does anyone else have an idea?

**Comment by mmckay99** [comment]
I'm not someone else but I have another idea:
- What if we leave it blank and have an arrow+message pointing to the sidebar saying "Hey, you haven't subscribed to any tags yet, why don't you click on them and follow!"

**Comment by ghost** [comment]
Could give them a few post that might be of interest like Python and Java

**Comment by ghost** [comment]
That could work, means they won't have tags they don't like (Bark bloatware)

**Comment by SCOTPAUL** [comment]
Yeah, that sounds like a good solution, as long as the message is quite prominent.

**Comment by mmckay99** [comment]
(https://github.com/projectgoav/studeso/commit/fea87cdffb83ba8cb4bed2ef15d5ac2faef1176f)

**Comment by SCOTPAUL** [comment]
Nice work.

**Comment by SCOTPAUL** [comment]
Unfollowing a tag that you don't currently follow causes a DoesNotExist exception to be thrown.

**Comment by mmckay99** [comment]
Have you got the latest version? Works for me?

**Comment by SCOTPAUL** [comment]
Yeah, try doing `/unfollow/a`, assuming you don't follow @a. An exception gets thrown then. Not something a user could really do without manually putting in the URL, but Leif'll probably check for it.

**Comment by mmckay99** [comment]
Should be fixed (https://github.com/projectgoav/studeso/commit/57df9c63d619d03d343ca8c28092a8d21ba3cc24).
