### ISSUE TITLE
Search button gets suspiciously wider in "add post" page

### ISSUE THREAD

**Issue by mmckay99** [projectgoav/studeso#45]
Is this just my browser?

**Comment by SCOTPAUL** [comment]
There's an extra bit of CSS for that page which makes the tag input box work properly. I think that might be why. It should really target the box specifically, but I didn't think it affected anything else so I left it.

**Comment by SCOTPAUL** [comment]
It's actually something in taggle.min.css that does it. I have no idea why that css targets buttons, I'll look into it later.

**Comment by mmckay99** [comment]
Cheers

**Comment by mmckay99** [comment]
Sorry if I'm being stupid here- but I just got the latest version and the button still changes size in "New Post"?

**Comment by SCOTPAUL** [comment]
Have you reset the server? Mine wouldn't change until I did.
