### ISSUE TITLE
New post from tag view

### ISSUE THREAD

**Issue by mmckay99** [projectgoav/studeso#47]
So in (https://github.com/projectgoav/studeso/commit/bb8503a5e15f26fa77065fc5276dc2e6f4384b7a) I added a new URL map, so if the user visits:

`.../new/java/c++`

They are taken to the "add post" page, but the "tags" field is pre populated with "java" and "c++".

Do you think we should have a button when viewing a tag "python", for "New post in _python_"?

**Comment by SCOTPAUL** [comment]
Yeah, I really like that idea.

**Comment by mmckay99** [comment]
Okay I'll try and add it

**Comment by mmckay99** [comment]
Done :smiley: https://github.com/projectgoav/studeso/commit/de126a087806e3d77bcfd8a62d0d08be72617e1e
