### ISSUE TITLE
Taggle won't accept uppercase tags

### ISSUE THREAD

**Issue by mmckay99** [projectgoav/studeso#48]
I just noticed that Taggle [(even the example one on the website)](http://sean.is/poppin/tags) converts entered tags to lowercase strings! :sob: 

I see four solutions:
- Switch from Taggle to another tag based entry system
- Modify Taggle
- Force all tags to be lowercase
- Introduce some new logic in the addPost function that will determine if a similar tag exists (so if we want to add "cs" and "CS" exists, then tag the post with "CS")

**Comment by SCOTPAUL** [comment]
I completely forgot about that. I don't really like the idea of switching tagging system now, when the presentation is tomorrow and an number of things could break. `.toLowerCase()` is only present a few times in taggle so changing it might not be that difficult.

**Comment by SCOTPAUL** [comment]
Users can have parts of their emails with capitals, which would make GLA.ac.uk have a different tag to gla.ac.uk too. We might have to force all tags, usernames and emails to become lowercase. That would address the uppercase letters in URLs issue too without slugifying I suppose.

Do you know if this can be done in the `clean()` method of the UserForm to avoid messing with the User model directly?

**Comment by mmckay99** [comment]
Hmm I agree: let's make all tags and emails to be lowercase on entry- but surely we can let users have Mixed Case names, just we make the associated tag all lowercase: SCOTPAUL -> "@scotpaul".

I'd guess `clean()` would be where to do it.

**Comment by SCOTPAUL** [comment]
I don't think we could, because then SCOTPAUL and ScoTPaul could be two different users and share a user tag. It also introduces some inconsistency, and wouldn't fix your issue with the URLs.

**Comment by mmckay99** [comment]
True

**Comment by SCOTPAUL** [comment]
Do you think we should automatically lower them or just add an error if they're uppercase?

**Comment by mmckay99** [comment]
Automatically lower I think- maybe we can do it in the form itself?

**Comment by SCOTPAUL** [comment]
The form's a ModelForm, so most of the stuff is done automatically. I'm not sure if it's better to do it in `clean()` or `save()`.

**Comment by SCOTPAUL** [comment]
Oh man, looking at [this](https://code.djangoproject.com/ticket/17561), it seems like email addresses are case-sensitive.

Edit: Then again, every site I've ever used has treated my email address as if it was case-insensitive.

**Comment by mmckay99** [comment]
And why do email addresses need to be case sensitive? If two users sign up with different emails only differing by case, there's no problem is there?

**Comment by SCOTPAUL** [comment]
It would result in a tag being generated with capitals. If you sign up with "paul@GLA.ac.uk", you introduce a "GLA.ac.uk" tag, which the user cannot actually use, since tags are lowercase.

**Comment by mmckay99** [comment]
Well why don't we just make it so that the address tag is lowercase'd version of the normal email?
If someone truly wants to sign up as paul@GLA.ac.uk then I think our website should just group them with gla.ac.uk people.

**Comment by SCOTPAUL** [comment]
Fair enough, that'd work. We still have the issue with usenames though. [This solution](http://stackoverflow.com/questions/24313201/convert-all-charfield-form-field-inputs-to-lowercase-in-django-forms) uses subclassing of CharField to handle it. What do you think about that?

**Comment by mmckay99** [comment]
You mean this?


`Try using a css text-transform with widget in your form like this:

class StripeSubscriptionSignupForm(forms.Form):
    coupon = forms.CharField(max_length=30,
        required=False,
        validators=[validate_coupon],
        label=mark_safe("<p class='signup_label'>Promo Code</p>")
        widget=TextInput(attrs={'style': 'text-transform:lowercase;'})
        )`

**Comment by SCOTPAUL** [comment]
No, I meant the accepted one. It seems like that might not actually work in our case though, `to_python()` doesn't actually enforce what is stored in the database, just in django objects.

**Comment by mmckay99** [comment]
I see. Well do you wnat to just force usernames to be all lowercase in the model?

**Comment by SCOTPAUL** [comment]
Ok. Do you want to work on that and I'll work on making InstitutionTags lowercase?

**Comment by mmckay99** [comment]
Okay- I need to take my dog out first. :dog:

**Comment by mmckay99** [comment]
I think this is working now- can we close the issue?

**Comment by SCOTPAUL** [comment]
Yeah, it seems to work now.
