### ISSUE TITLE
When a user tries to tag another user

### ISSUE THREAD

**Issue by mmckay99** [projectgoav/studeso#50]
At the moment if mm3 tries to tag "lDicks" in his post, the ldicks tag is just ignored. Do we want to let users tag other users?

**Comment by SCOTPAUL** [comment]
I don't think we should. Since the only thing that supports tagging is posts, it'd be uncommon for a user to want to tag another user in a post. It would also mean that clicking on a username would show all the posts they're tagged in, rather than all the ones they authored.

**Comment by SCOTPAUL** [comment]
I'm not sure if we handle users with usernames that are the same as existing tags though, e.g. making a user called "admin". I'm on mobile just now so I can't test it myself.

**Comment by mmckay99** [comment]
Good thinking, yes we get an "Integrity error" (we can't create a user tag with the same name as an existing tag). Do we want to stop people creating usernames that are already existing tags?

**Comment by SCOTPAUL** [comment]
I suppose so. Ugh, today has been full of so many of these little bugs.

**Comment by mmckay99** [comment]
I'll try and patch that one.

**Comment by mmckay99** [comment]
Should be fixed (https://github.com/projectgoav/studeso/commit/96a05b00f0941c1ade5b111ccb3959842698470c).
