### ISSUE TITLE
All these little changes

### ISSUE THREAD

**Issue by ghost** [projectgoav/studeso#51]
I wanted to say thanks to @mmckay99 and @SCOTPAUL for all the work you guys did trying to error proof the site, but realistically I think we should call time on it, we've put so much work into this and we should focus on uploading the changes to pythonanywhere and putting it up on Leif's site so we can prepare for the demo tomorrow

**Comment by SCOTPAUL** [comment]
As I said in the Facebook message, I'm not sure we can upload it without @projectgoav

**Comment by ghost** [comment]
We can do it tomorrow before the presentation
