### ISSUE TITLE
Urgent! Help button in top menu bar?

### ISSUE THREAD

**Issue by mmckay99** [projectgoav/studeso#53]
Is this redundant now, can we remove it?

Going to be awkward if Leif asks us to click it...

**Comment by ghost** [comment]
Think @projectgoav said its used for JSON stuff, we can check tomorrow

**Comment by mmckay99** [comment]
Awww right right okay dokay

**Comment by projectgoav** [comment]
Help gets the information via JSON. It's required to show help. Please don't remove.
