### ISSUE TITLE
Help on following a tag seems half complete

### ISSUE THREAD

**Issue by SCOTPAUL** [projectgoav/studeso#56]
As shown here:
![screenshot from 2015-03-26 12 29 29](https://cloud.githubusercontent.com/assets/6534210/6846169/e2151f62-d3b3-11e4-8dc9-7eb24a74dfa1.png)

It also seems to be a link rather than plain text.

**Comment by SCOTPAUL** [comment]
Also, if you are viewing multiple tags and click next in the help a few times, the page will stay dark but not show any more help. This isn't a big deal but it happened in the presentation the other day.

**Comment by projectgoav** [comment]
I noticed the first one earlier. I'm fixing it the now. As for the second, I'll take a look.
