### ISSUE TITLE
Leif's Presentation Gripes / TODOs

### ISSUE THREAD

**Issue by mmckay99** [projectgoav/studeso#6]
Presentation went really well today, good effort all round chaps :+1: 
1. For the URL Mapping, I think he wanted more consistency between the "view tags", and "tag search". I agree, not sure what "tag search" even does, isn't that the same as normal search?
2. I personally think in the URL mappings, we should have "/users/mikey/" instead of "/user/mikey/". It makes more sense when they want to view all users, they would visit "/users/" I think. I guess we could easily setup a redirect so "user" -> "users" and "post" -> "posts".
3. Leif mentioned adding attributes into the ER diagram. Do we want to add them to the current one? Or have another, more detailed ER diagram? Would this introduce redundancy?
4. Making the "Bark! Search, post, bark! ..." and the dog logo part of the base HTML, which would appear on every page. _I think we should have the whole banner on every page but I remember you guys weren't sure?_
5. Moving the search bar. I guess we're going to make this part of the base.html banner as above, but is it's current location OK? I don't think it's too bad to be honest, what do you guys think?
6. In the "Popular Tags" section, we have "More..." and "All Tags". Aren't these really the same thing? And the two links seem quite small, maybe we could combine into a larger button?

**Comment by SCOTPAUL** [comment]
1. Yeah, I think you're right, it should probably just be a normal search. At the time I think I wasn't sure if we would support searching the body of a post, it should have been renamed.
2. Yep. I don't really think we need the redirect though.
3. I think we could add tables of attributes off to the side, which would still allow the relations to be simple while including that extra detail in the same diagram.
4. I like the idea of having the dog logo and caption on every page except possibly the homepage, the large banner @projectgoav tried recently seemed to get the brand across strongly. I guess we could have that large banner for a logged out user, and then revert to the more basic one when they register?
5. It could go above the followed tags, that way it would still scroll with the page without being in the top left. Not sure on that one.
6. I think 'More...' shows a dropdown of tags you follow, and 'All Tags' shows all of the tags ever created, ranked by popularity or something. We could probably move that to somewhere less prominent and make 'More...' more obvious.

**Comment by projectgoav** [comment]
1 - Yeah, should just be a normal search url. We'll write a pretty back-end bit of code to decide wither it's a tag, username or post and display results accordingly?

2 - I agree with @SCOTPAUL 

3 - I also agree with @SCOTPAUL 

4 - Yeah, we're going to put the logo on every page. Once I figure out how to get the search bar and button centered the banner should look like:

```
[LOGO] Bark!                         [SEARCH BOX]Go Fetch!                About Help Login etc
```

I think we should have a bigger banner on the homepage to welcome people and give it a big title and branding but this will only appear on the homepage. Perhaps even only appear to users who're not logged in?
With the common header, I suggest using a smaller version of the dog image, so we're not using up loads of space when the users are viewing proper content.

5 - ^ As above. TL;DR -> I think middle.

6 - As @SCOTPAUL  says : More adds more tags to list, be it more popular ones or more tags the user follows. We could even add more categories and fill up that column even more! All Tags goes to a page and lists all the tags Bark! has and knows about.

**Comment by ghost** [comment]
I don't really have a lot to say regarding all this but I agree with @SCOTPAUL and @projectgoav, we can try organise this and arrange how we implement the back end on Thursday (which I may be a few minutes late for, start without me I'll catch up!)
