### ISSUE TITLE
Auto Complete

### ISSUE THREAD

**Issue by projectgoav** [projectgoav/studeso#7]
Found this wee project on Github: https://github.com/LeaVerou/awesomplete

We might need to generate the contents of the autocomplete by backend code each time users searches however, to make sure it has all the tags etc added.

**Comment by mmckay99** [comment]
I've tried to make the search as flexible and open as possible- so if the user searches "java" all related tags such as "java-help", or "javascript", or "java-code" will appear.

I'd hope this mitigates some of the reasons we wanted to have autocomplete- so can we close this issue?

**Comment by ghost** [comment]
...was just about to close this haha
