### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by projectgoav** [projectgoav/studeso#8]
_If you have any I've missed or want to add, comment below_

Frontend
- [x]  Base Template
- [x] Header Template
- [x] Footer Template
- [x] Autocomplete
- [x] Pages
  - [x] Homepage
  - [x] User Homepage
  - [x] Post View
  - [x] Profile View
  - [x] Add post
  - [x] Add comment
  - [x] Login/Out
  - [x] Password Functions
  - [x] Profile Update

Backend
- [x] Models
  - [x] Users
  - [x] Tags
  - [x] Posts
  - [x] Comments
- [x] Views
  - [x] Homepage
  - [x] User Homepage
  - [x] Post View
  - [x] Profile View
  - [x] Add post
  - [x] Add comment
  - [x] Rating
  - [x] Profile Update
- [x] Search
- [x] Login
- [x] Register
- [x] Logout
- [x] Password Functions

Extra
- [x] Population Script(s)
- [x] Email service

**Comment by ghost** [comment]
I'm just looking at this and realising we seem to have almost, if not everything complete, well done guys! :D Couple of things I'm interested to know:

1) Will there be a footer template ( @projectgoav I think I mentioned this to you but you said to leave it)

2) What needs to be/has been done about autocomplete?

**Comment by projectgoav** [comment]
I just put these up when we first started. I thougth autocomplete was good for searching, but dunno how we could get that done. As for footer and header, I doubt we'll put them in, but just incase they are there.
